<a href="https://colab.research.google.com/github/shoulhafiz/python_data_science/blob/master/linear_algebra_refresh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

## Determinant

<img src="https://miro.medium.com/max/3426/1*-ycNEMicMOIR8WvzcBzERA@2x.jpeg" width="50%">

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.det.html



In [3]:
np.linalg.det(x)

-2.0000000000000004

## Transpose

<img src="https://www.studymite.com/wp-content/uploads/2018/12/transpose.jpg" width="50%">


In [9]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
y.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

## Dot product / matrix multiplication

<img src="http://www.mathcs.emory.edu/~cheung/Courses/554/Syllabus/9-parallel/FIGS/mat-mult01.gif" width="50%">

In [10]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b = np.array([[6,3],[5,2],[4,1]])
b

array([[6, 3],
       [5, 2],
       [4, 1]])

In [13]:
a.shape, b.shape

((2, 3), (3, 2))

In [12]:
a.dot(b)

array([[28, 10],
       [73, 28]])

## Convolution

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Comparison_convolution_correlation.svg/400px-Comparison_convolution_correlation.svg.png" width="30%">

In [0]:
n = [1,2,3,4,5]
kernel = [2,2]

In [20]:
np.convolve(n, kernel, mode= 'same')

array([ 2,  6, 10, 14, 18])

In [21]:
np.convolve(n, kernel, mode= 'full')

array([ 2,  6, 10, 14, 18, 10])

In [22]:
np.convolve(n, kernel, mode= 'valid')

array([ 6, 10, 14, 18])