<a href="https://colab.research.google.com/github/shoulhafiz/python_data_science/blob/master/multinomial_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/political-landscape/political-landscape.json

--2019-11-05 03:25:31--  https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/political-landscape/political-landscape.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2020656 (1.9M) [text/plain]
Saving to: ‘political-landscape.json’

political-landscape 100%[===================>]   1.93M  --.-KB/s    in 0.06s   

2019-11-05 03:25:31 (32.7 MB/s) - ‘political-landscape.json’ saved [2020656/2020656]



In [0]:
import json

with open('political-landscape.json') as fopen:
  politics = json.load(fopen)

In [4]:
politics.keys()

dict_keys(['kerajaan', 'pembangkang'])

In [5]:
politics['kerajaan'][:10]

['Di Aloq Staq tadi kayuh gerek 3km, tapi makan tgh hari pekena ikan pekasam, gulai, daging bakar, tapai pulut Balik kena kayuh lebih lagi ni',
 'Kayuh gerek pagi tadi bersama orang muda Gen Y Kedah di Dataran Menara Alor Setar Orang Kedah memang sempoi',
 'Apa habaq org Kedah? Alhamdulillah, sy kini di Alor Star utk lawatan ke negeri Jelapang Padi, bermula dgn prtemuan brsm kpimpinan UMNO Kedah',
 'Saya berbesar hati merasmikan Medan Selera Lundu Ini merupakan projek yang dekat di hati Tok Nan yang sentiasa peka denyutan nadi Sarawak',
 'Salam Jumaat Khatib tadi mengingatkan bhw hubungan yg baik antara rakyat pemimpin penting utk mewujudkan negara yg sejahteraInsyaAllah',
 'Anasir2 negatif dlm dan luar negara boleh terus menghasut namun mrk tidak mampu menafikan kejayaan2 negaraku ini',
 'Salah satu pemandangan kegemaran saya di Sarawak Selamat pagi Hari ini saya akan ke Lundu pula untuk program bersama rakyat See you there',
 'Inilah semangat 1Malaysia yang sebenar di mana kita merai

In [6]:
politics['pembangkang'][:10]

['Kit Siang: Criticism of TV3 journalist is valid Mkini',
 'Pua: I hope Salleh is just feigning ignorance on 1MDB Mkini',
 'Three tutors can school Salleh on govt scandals, says Kit Siang Mkini',
 'Kalau benar antiIslam, sudah lama DAP diharamkan bawah Akta Pertubuhan Persatuan Roketkini',
 'Look east to Sabah, Sarawak, DAP tells opposition parties V Anbalagan FMT',
 'Guan Eng challenges Ku Nan to TV debate on Penang FT Susan Loone Mkini',
 'Hafiz Yatim Mkini',
 'Minister: BMF scandal bigger than 1MDB Mkini',
 'PAS arithmetic not right, Dr M responds to quit pact proposal Alyaa Azhar Mkini',
 'Kit Siang hopes Zaid will be team player, not prima donna Zikri Kamarulzaman Mkini']

In [7]:
!wget https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/emotion/love-twitter-malaysia.json

--2019-11-05 03:33:56--  https://raw.githubusercontent.com/huseinzol05/Malaya-Dataset/master/emotion/love-twitter-malaysia.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5839783 (5.6M) [text/plain]
Saving to: ‘love-twitter-malaysia.json’

love-twitter-malays 100%[===================>]   5.57M  --.-KB/s    in 0.07s   

2019-11-05 03:33:56 (82.7 MB/s) - ‘love-twitter-malaysia.json’ saved [5839783/5839783]



In [8]:
    
with open('love-twitter-malaysia.json') as fopen:
  love = json.load(fopen)
love[:10]

['Oh ternyata semua karena rindu beb..',
 'Toklaki : Syg jual la sokok tigo tuu\nLily : mari la gambar. Keno ado gambar goni\nToklaki : ambik la gambar\nLily : t https://t.co/zmlnkXFPbd',
 '@farynn01 Aku pun rindu nak terima kedatangan hang. Nnt ada rezeki jumpa weh could use a friendly faces. Sikit ja l https://t.co/IVOPUig3Qx',
 '@mommy_elzar Untung badan aku kecil, gak berat. Cuma gak ada yang bilang cinta aja..',
 'Itu baru cinta katanya https://t.co/h3gX29oohF',
 'Baby sayang kau laa lahanat ! please la hantar ni org p tg rambutan atau bukit padang kah.. mental disorder banar ! https://t.co/nUNkbhVJ5I',
 'Hmmm rindu ke tu',
 '@SulaimanAlis sebelom ni syg tak melimpah ruah ke ? asye asye jela ?',
 'Sayang mandikan. Nak sayang duduk sebelah..nak sayang suapkan.. aloloo abang zarill..\n#AkuYangKauTinggalkan',
 '14052019M09091440H2002020132HH\nADA SEBAB BERTEMU\n\nKalau rindu seseorang berdoalah kepada Allah dengan doa yang ba https://t.co/Bx0D3dc8Uo']

In [9]:
len(love), len(politics['kerajaan']), len(politics['pembangkang'])

(59242, 15120, 7457)

In [0]:
import random

sample_love = random.sample(love,500)
sample_kerajaan = random.sample(politics['kerajaan'],500)
sample_pembangkang = random.sample(politics['pembangkang'],500)

In [0]:
import re

def cleaning(string):
  string = re.sub(
        'http\S+|www.\S+',
        '',
        ' '.join(
            [
                word
                for word in string.split()
                if word.find('#') < 0 and word.find('@') < 0
            ]
        ),
    )
  string = re.sub('[^A-Za-z ]+', ' ', string)
  string = re.sub(r'[ ]+', ' ', string).strip()
  return string.lower()



In [14]:

love[0], cleaning(love[0])



('Oh ternyata semua karena rindu beb..', 'oh ternyata semua karena rindu beb')

In [15]:
X = sample_love + sample_kerajaan + sample_pembangkang
len(X)


1500

In [17]:

# 0 = love
# 1 = kerajaan
# 2 = pembangkang

Y = [0] * len(sample_love) + [1] * len(sample_kerajaan) \
+ [2] * len(sample_pembangkang)

for i in range(len(X)):
  X[i] = cleaning(X[i])

X[:5]


['sayang banget padamu prof',
 'rindu biak kelas sidaknya x pernah mandang rendah kt org lain kdk urg disitok hmmm',
 'hahahahahaha mesti rindu kerepek anum kan semua org',
 'selamat menikmati hari jum at mari tebarkan senyum dan berikan kasih sayang supaya hidup lebih berkah dan lebih be',
 'hahahahaha gurau jela rindu sume orang kecuali yang dah ade gf']

In [18]:

x = ['saya suka ayam', 'saya suka daging', 'saya tak makan ayam']
x

v = list(set(' '.join(x).split()))
v


['suka', 'saya', 'daging', 'tak', 'ayam', 'makan']

In [19]:
import numpy as np

bow = np.zeros((len(x), len(v)))
bow


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
for no, string in enumerate(x):
  for word in string.split():
    if word in v:
      bow[no, v.index(word)] += 1

bow

array([[3., 3., 0., 0., 3., 0.],
       [3., 3., 3., 0., 0., 0.],
       [0., 3., 0., 3., 3., 3.]])

In [26]:
vocab = ''.join(X).split()
vocab = list(set(vocab))
len(vocab)


6577

In [0]:
bow = np.zeros((len(X), len(vocab)))

In [0]:
for no, string in enumerate(X):
  for word in string.split():
    if word in vocab:
      bow[no, vocab.index(word)] += 1

In [29]:
y, count_labels = np.unique(Y, return_counts = True)
print(y, count_labels)


[0 1 2] [500 500 500]


In [30]:
labels = {}
for no, label in enumerate(y):
  labels[label] = count_labels[no] / sum(count_labels)

labels

{0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}

In [31]:
total_freqs = {}

for label in y:
  total_freqs[label] = bow[Y == label].sum()

total_freqs

{0: 6517.0, 1: 4951.0, 2: 5825.0}

In [32]:
probability_table = np.zeros((len(vocab), len(labels)))

for label in y:
  p = (bow[Y == label].sum(axis = 0) + 1) / (total_freqs[0] + len(vocab))
  probability_table[:,label] = p

probability_table

array([[7.63708569e-05, 2.29112571e-04, 7.63708569e-05],
       [7.63708569e-05, 7.63708569e-05, 1.52741714e-04],
       [7.63708569e-05, 7.63708569e-05, 1.52741714e-04],
       ...,
       [7.63708569e-05, 7.63708569e-05, 7.63708569e-05],
       [1.52741714e-04, 7.63708569e-05, 7.63708569e-05],
       [7.63708569e-05, 7.63708569e-05, 7.63708569e-05]])

In [33]:
y, count_labels = np.unique(Y, return_counts = True)
print(y, count_labels)

labels = []
for no, label in enumerate(y):
  labels.append(count_labels[no] / sum(count_labels))

labels

[0 1 2] [500 500 500]


[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]

In [35]:
enumerator=(bow.dot(probability_table)) * labels
denominator= enumerator.sum(axis=1, keepdims=True)
enumerator/denominator

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[0.95721925, 0.02139037, 0.02139037],
       [0.74172185, 0.1192053 , 0.13907285],
       [0.70261438, 0.12091503, 0.17647059],
       ...,
       [0.18561151, 0.2       , 0.61438849],
       [0.24471299, 0.29003021, 0.4652568 ],
       [0.13651877, 0.13822526, 0.72525597]])

In [42]:
string = 'saya sayang kerajaan'

new_bow = np.zeros((1, len(vocab)))

for word in string.split():
  if word in vocab:
    new_bow[0, vocab.index(word)] += 1

enumerator = (new_bow.dot(probability_table)) * labels
denominator = enumerator.sum(axis = 1, keepdims = True)
enumerator / denominator

array([[0.25983146, 0.61657303, 0.12359551]])